# Generated by Django 2.1.3 on 2018-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32)),
                ('balance', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderAddress', models.CharField(max_length=32)),
                ('recipientAddress', models.CharField(max_length=32)),
                ('signature', models.CharField(max_length=32)),
            ],
        ),
    ]
